services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_DSN: postgres://postgres:postgres@db/bus_outbox
      BOOTSTRAP_SERVERS: kafka:9092
    command: migrate

  db:
    image: postgres:16-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus_outbox

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092"
