services:
  app:
    build:
      context: .
      target: main
    depends_on:
      - db
      - kafka
    environment:
      DB_DSN: postgres://postgres:postgres@db/bus_outbox
      BOOTSTRAP_SERVERS: kafka:9092
    command: migrate

  test:
    build:
      context: .
      target: test
    depends_on:
      - db
      - kafka
    volumes:
      - ./tests:/tests
    working_dir: /tests
    environment:
      DB_DSN: postgres://postgres:postgres@db/bus_outbox
      BOOTSTRAP_SERVERS: kafka:9092
    command: pytest -s --tb=native -v -rsxX

  db:
    image: postgres:16-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus_outbox

  kafka:
    image: bitnami/kafka:3.7
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
