services:
  app:
    build: .
    depends_on:
      - db
    environment:
      DB_DSN: postgres://postgres:postgres@db/bus_producer

  db:
    image: postgres:16-alpine
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus_producer
